### ISSUE TITLE
Missing --file option in run.py

### ISSUE THREAD

**Issue by tmayberry** [vivek3141/ghostbuster#1]
Thanks for sharing this code with everyone!  The documentation says that you can run it against a file using the --file option but that seems to be missing in run.py.  There are also a couple other small errors that popped up trying to get this to run.  If there is an openai.config file in the directory, it tries to load a hardcoded version of it from a specific home directory instead of the one in the local directory.  It also tries to read a file called best_features.txt from the model directory which doesn't exist (I copied features.txt to this name and it seems to have fixed it).

Edit: I see it is actually just a documentation issue, the right program should be classify.py.

**Comment by vivek3141** [comment]
Hi, sorry! I was in process of reformatting a lot of the code. I'll work on fixing the README, thanks for bringing it up
