### ISSUE TITLE
Calling ghostbuster in code on in-memory text

### ISSUE THREAD

**Issue by Nonameentered** [vivek3141/ghostbuster#3]
Hello!

Thanks for sharing this project and I look forward to exploring its applications. In the Readme, there are instructions on how to call ghostbuster on a text file and just wanted to check if you could provide instructions to import ghostbuster in a `.py` file and what function I might be able to call to have it evaluate strings I store in-memory in Pandas?

**Comment by vivek3141** [comment]
At the moment no, but feel free to convert the code in classify.py into a function and call it from there!
