### ISSUE TITLE
Issue with Tokenizer Compatibility in classify.py

### ISSUE THREAD

**Issue by 2020lwh567** [vivek3141/ghostbuster#9]
Since 2024-01-04, according to [https://platform.openai.com/docs/deprecations](https://platform.openai.com/docs/deprecations), OpenAI has deprecated the use of `ada` and `davinci`. The replacements are now `babbage-002` for `ada` and `davinci-002` for `davinci`. 
I've encountered an issue in the `classify.py` file where the length discrepancy between the `trigram` and `ada` tokens is causing errors. The specific error message is: `ValueError: operands could not be broadcast together with shapes (116,) (115,) `. This misalignment is likely due to the recent changes in models.
Here is my `input.txt` for reference:
`In conclusion, "12 Years a Slave" effectively analyzes the themes of collectivism and individualism to portray the institution of slavery as a worldwide issue. The film gracefully showcases the dehumanization of black people through systematic prejudices, generalizations, stereotyping, and discrimination. By highlighting the power of collectivism and individualism in resisting and transcending slavery, it serves as a call to action for a global recognition of the need to dismantle systemic oppression. The film's portrayal of this historical struggle encourages viewers to confront their own biases and advocate for a more inclusive and equitable world.`

I've attempted to replace the tokenizer in `utils/symbolic.py` with `cl100k_base`, `p50k_base`, and `r50k_base`, but the issue persists.
I would appreciate your assistance in resolving this matter.  Thank you for your time and consideration.

**Comment by vivek3141** [comment]
Hey, I've fixed this and re-trained the models with babbage and davinci. The updated data is in the ghotbuster-data repo.

The only problem is that the performance is now a little bit worse! I hypothesize this is due to babbage being more similar to davinci than ada, so leveraging any information in their differences becomes less useful. When I get some more free time, I'll try and move everything to open-source models. I had some extremely promising results with LLaMA, and managed to beat out davinci/ada on a couple scenarios without much work.

**Comment by 2020lwh567** [comment]
> Hey, I've fixed this and re-trained the models with babbage and davinci. The updated data is in the ghotbuster-data repo.
> 
> The only problem is that the performance is now a little bit worse! I hypothesize this is due to babbage being more similar to davinci than ada, so leveraging any information in their differences becomes less useful. When I get some more free time, I'll try and move everything to open-source models. I had some extremely promising results with LLaMA, and managed to beat out davinci/ada on a couple scenarios without much work.

OK, thousands of thanks for your kindness~
